// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHTXM0EqN60_MwuoeCKvAKu25bZDtVaZE',
    appId: '1:377442643095:web:1a59f7e6c7e50fd1870dd2',
    messagingSenderId: '377442643095',
    projectId: 'chat-d3f86',
    authDomain: 'chat-d3f86.firebaseapp.com',
    storageBucket: 'chat-d3f86.firebasestorage.app',
    measurementId: 'G-P1GBHVYJ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrhAdvwu2wrt_XwF-yWvh4j-OAQGxsoVM',
    appId: '1:377442643095:android:be915d534fd2d295870dd2',
    messagingSenderId: '377442643095',
    projectId: 'chat-d3f86',
    storageBucket: 'chat-d3f86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHa3N10XIK3lnm71tgR4yTMoc7L1pPoRE',
    appId: '1:377442643095:ios:b5f4d170f3c96d34870dd2',
    messagingSenderId: '377442643095',
    projectId: 'chat-d3f86',
    storageBucket: 'chat-d3f86.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHa3N10XIK3lnm71tgR4yTMoc7L1pPoRE',
    appId: '1:377442643095:ios:b5f4d170f3c96d34870dd2',
    messagingSenderId: '377442643095',
    projectId: 'chat-d3f86',
    storageBucket: 'chat-d3f86.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHTXM0EqN60_MwuoeCKvAKu25bZDtVaZE',
    appId: '1:377442643095:web:b91571be096459b3870dd2',
    messagingSenderId: '377442643095',
    projectId: 'chat-d3f86',
    authDomain: 'chat-d3f86.firebaseapp.com',
    storageBucket: 'chat-d3f86.firebasestorage.app',
    measurementId: 'G-16QLRRZC2W',
  );
}
